# Generates docs/header.svg, the README banner.
#
#     mix run docs/graphics.exs
#
# Draws the XX handshake as a sequence diagram: the token list of each message
# comes straight from `Noise.Pattern.from_name("XX")`, so the picture cannot
# drift from what the library actually sends. A particle travels the three
# messages in order and settles on the Split() line where the transport
# ciphers are derived.
defmodule Header do
  @moduledoc false

  @ink "#e6e6e9"
  @muted "#606069"
  @accent "#4ade80"
  @font "ui-monospace, 'JetBrains Mono', 'Fira Code', monospace"

  # lane geometry
  @x_ini 495
  @x_resp 705
  @y_names 34
  @y_first 68
  @y_step 38

  # one full trip of the particle; it reaches Split() at @arrive and rests there
  @dur "24s"
  @arrive 0.85

  defp fmt(f), do: :erlang.float_to_binary(f / 1, decimals: 2)

  defp lane(:ini), do: @x_ini
  defp lane(:resp), do: @x_resp
  defp other(:ini), do: :resp
  defp other(:resp), do: :ini

  defp label(:ini, tokens), do: "-> " <> Enum.join(tokens, ", ")
  defp label(:resp, tokens), do: "&lt;- " <> Enum.join(tokens, ", ")

  # both lifelines, bleeding past the card edges, with a gap for the role name
  defp lanes do
    Enum.map_join([@x_ini, @x_resp], " ", fn x ->
      "M #{x} -1 V #{@y_names - 12} M #{x} #{@y_names + 5} V 221"
    end)
  end

  # {y, from_role, tokens} per handshake message
  defp messages(tokens) do
    tokens
    |> Enum.with_index()
    |> Enum.map(fn {{role, toks}, i} -> {@y_first + i * @y_step, role, toks} end)
  end

  defp arrow({y, role, toks}) do
    xa = lane(role)
    xb = lane(other(role))
    d = if role == :ini, do: -6, else: 6

    """
        <line x1="#{xa}" y1="#{y}" x2="#{xb}" y2="#{y}" stroke="#{@ink}" stroke-opacity="0.55" stroke-width="1.1"/>
        <path d="M #{xb} #{y} l #{d} -3 M #{xb} #{y} l #{d} 3" stroke="#{@ink}" stroke-opacity="0.55" stroke-width="1.1" fill="none" stroke-linecap="round"/>
        <text x="#{(@x_ini + @x_resp) / 2}" y="#{y - 7}" font-size="9" letter-spacing="1.5" fill="#{@muted}" text-anchor="middle">#{label(role, toks)}</text>
    """
  end

  # the particle's route: down the sender's lane, across, down the receiver's lane, ...
  defp route(msgs, y_split) do
    [{y0, role0, _} | _] = msgs

    hops =
      Enum.map_join(msgs, " ", fn {y, role, _} ->
        "L #{lane(role)} #{y} L #{lane(other(role))} #{y}"
      end)

    {_, last_role, _} = List.last(msgs)
    "M #{lane(role0)} #{y0 - 30} #{hops} L #{lane(other(last_role))} #{y_split}"
  end

  def svg do
    %Noise.Pattern{tokens: tokens} = Noise.Pattern.from_name("XX")
    msgs = messages(tokens)
    y_split = @y_first + length(msgs) * @y_step
    arrive = fmt(@arrive)
    pulse = fmt(@arrive + 0.04)

    """
    <svg xmlns="http://www.w3.org/2000/svg" width="820" height="220" viewBox="0 0 820 220" role="img" aria-label="Noise Protocol — XX handshake: -> e, &lt;- e, ee, s, es, -> s, se, then Split()">
      <desc>Generated by docs/graphics.exs — the XX handshake pattern as a sequence diagram, tokens taken from Noise.Pattern. Do not edit by hand.</desc>
      <defs>
        <clipPath id="card"><rect x="1" y="1" width="818" height="218" rx="11"/></clipPath>
        <path id="route" d="#{route(msgs, y_split)}"/>
      </defs>
      <rect x="0.5" y="0.5" width="819" height="219" rx="12" fill="#050505" stroke="#1c1c1f"/>
      <g clip-path="url(#card)" font-family="#{@font}">
        <path d="#{lanes()}" stroke="#{@ink}" stroke-opacity="0.22" fill="none"/>
        <text x="#{@x_ini}" y="#{@y_names}" font-size="9" letter-spacing="3" fill="#{@muted}" text-anchor="middle">INITIATOR</text>
        <text x="#{@x_resp}" y="#{@y_names}" font-size="9" letter-spacing="3" fill="#{@muted}" text-anchor="middle">RESPONDER</text>
    #{Enum.map_join(msgs, "", &arrow/1)}
        <line x1="#{@x_ini}" y1="#{y_split}" x2="#{@x_resp}" y2="#{y_split}" stroke="#{@accent}" stroke-opacity="0.45" stroke-dasharray="2 4"/>
        <circle cx="#{@x_ini}" cy="#{y_split}" r="2.5" fill="#{@accent}">
          <animate attributeName="r" values="2.5;2.5;4.5;2.5" keyTimes="0;#{arrive};#{pulse};1" dur="#{@dur}" repeatCount="indefinite"/>
        </circle>
        <circle cx="#{@x_resp}" cy="#{y_split}" r="2.5" fill="#{@accent}">
          <animate attributeName="r" values="2.5;2.5;4.5;2.5" keyTimes="0;#{arrive};#{pulse};1" dur="#{@dur}" repeatCount="indefinite"/>
        </circle>
        <text x="#{(@x_ini + @x_resp) / 2}" y="#{y_split + 14}" font-size="9" letter-spacing="3" fill="#{@accent}" text-anchor="middle">SPLIT</text>
        <circle r="2.2" fill="#{@ink}" opacity="0.6">
          <animateMotion dur="#{@dur}" repeatCount="indefinite" rotate="none" calcMode="linear" keyPoints="0;1;1" keyTimes="0;#{arrive};1">
            <mpath href="#route"/>
          </animateMotion>
          <animate attributeName="opacity" values="0.6;0.6;0;0" keyTimes="0;#{arrive};#{pulse};1" dur="#{@dur}" repeatCount="indefinite"/>
        </circle>
      </g>
      <g font-family="#{@font}" text-anchor="middle">
        <text x="244" y="115" font-size="24" font-weight="300" letter-spacing="8" fill="#{@ink}">NOISE PROTOCOL</text>
        <text x="240" y="145" font-size="9" letter-spacing="3" fill="#{@muted}">HANDSHAKE FRAMEWORK · ELIXIR · REVISION 34</text>
      </g>
    </svg>
    """
  end
end

File.write!("docs/header.svg", Header.svg())
